title:        Hangouts
url:          http://hangouts.apievangelist.com
version:      1.1.1
author:
  name:       'Kin Lane'
  email:      'info@apievangelist.com'
markdown:     rdiscount
permalink:    pretty
pygments:     true

permalink: /:categories/:year/:month/:day/:title
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

paginate: 100
paginate_path: "/news/page:num"

production_url : http://hangouts.apievangelist.com

BASE_PATH : http://hangouts.apievangelist.com

categories_path : /categories.html
tags_path : /tags.html
